### PR TITLE
Repo Serves Clients + Client App Redone

### PR DESCRIPTION
**Pull request by justincpresley**
This Pull accomplishes two tasks:
* sort out how a repo node replies to interests
* redo the client application

**This Pull DOES NOT accomplish client file fetching.** This is in the process of being done, and only sets up how the repo will respond.

_**New Client Functionality:**_

All functions (dump, insert, delete, fetch) are done by doing:
- python3 main.py fetch
- python3 main.py delete
- python3 main.py dump
- python3 main.py insert

Some of these (in fact all of them) have their own arguments (indicated by a -letter) that you need to fulfill for example:
- python3 main.py insert -f "/file1" -p "./examples/t.txt"

If you run the client application, it will tell you this entire process. The application will correct you.

_**New Repo Functionality:**_

The repo will respond with either a NACK, BLOB, or LINK data packet. The first two self-explanatory, the latter being the correct prefix to go to (does not include segmenting). For example if the client wants /drepo/main/file1/seg=0, then the link will provide /drepo/id/node5/file1 for example. The Client is responsible getting what packets it needs.

While the Repo can not be tested yet. **_The New Client should be tested before pushing it to main._**

### CODE REVIEW

**Comment by ZixuanZhong** [comment]
you should use `global_view_2` instead of `global_view` everywhere. Plz change that in `ndn_distributed_repo/handle_protocol/read_handle.py`, thx!

**Review by ZixuanZhong — COMMENTED** [review]
LGTM, Can merge after testing.

**Comment by justincpresley** [comment]
I sorted out the database problems. Currently, I am just having trouble connecting nodes together. For some reason, it sometimes prints EXPIRE messages for two of the nodes on all three nodes. This makes it so that when a client sends an insert command, it doesnt have enough nodes within the repo to replicate it, failing.

Maybe this is an issue with the Expire message?

**Review by ZixuanZhong — COMMENTED** [review]
LGTM

**Pull request merged**
